added in mobile friendly styling
Vero-Ventures/accubot pull request #135
Opened 2024-07-11 18:59 UTC by shawnbirring

Modified the home, privacy policy and terms of service pages to be mobile friendly

2024-07-11 21:24 UTC, michaeleii requested changes

2024-07-11 21:24 UTC, michaeleii commented on frontend/components/signin.tsx
>  const SignInButton = () => {
I thought shadcn was installed. Can we not use the `Button` component here? 

Might be able to get rid of some tailwind classes.

2024-07-11 21:24 UTC, michaeleii commented on frontend/components/homebutton.tsx
> +      className="inline-block bg-blue-600 text-white px-6 py-3 rounded-lg shadow-md transition-colors duration-300 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:ring-opa
`buttonVariants` function from shadcn `Button` can be used to style this and reduce class names.

2024-07-11 21:24 UTC, michaeleii commented on frontend/app/privacy-policy/page.tsx
> +const privacyPolicies = [
Instead of using a javascript array might be easier to write it as markdown and then use a markdown parser to convert it to html and use tailwindcss typography to style the html.

https://github.com/tailwindlabs/tailwindcss-typography

Just a suggestion but this will work for now.

2024-07-12 20:40 UTC, michaeleii approved these changes

2024-07-12 20:42 UTC, scottchen98 approved these changes

2024-07-12 20:44 UTC, merged